/**
 * exportGenerators.js
 * 
 * Pure serialization logic for StudyFlow export formats (Markdown, PlainText, JSON).
 * Decoupled from React UI for maximum testability and reusability.
 */

export function generateMarkdownContent(studyData) {
  if (!studyData) return '';
  const { filename, notes = [], quiz = [], meta = {} } = studyData;
  const pers = meta?.personalization;

  let md = `# StudyFlow Revision Guide: ${filename || 'Lecture Material'}\n\n`;

  if (pers?.subject || pers?.academicLevel || pers?.focus) {
    md += `> **Course**: ${pers.subject || 'General'} | **Level**: ${pers.academicLevel || 'Undergraduate'} | **Focus**: ${pers.focus || 'Comprehensive'}\n\n`;
  }

  md += `**Document Metadata**: ${meta?.totalPages || 1} Pages/Slides | ${(meta?.totalWords || 0).toLocaleString()} Words | ${meta?.chunksCount || 0} RAG Chunks | Synthesized with ${meta?.modelUsed || 'Gemini Flash'}\n\n`;
  md += `---\n\n`;

  md += `## 📚 Core Revision Notes\n\n`;
  notes.forEach((section, idx) => {
    md += `### ${idx + 1}. ${section.topic}\n\n`;
    (section.points || []).forEach((point) => {
      md += `- ${point}\n`;
    });
    md += `\n`;
  });

  md += `---\n\n`;
  md += `## 📝 Interactive Multiple-Choice Quiz\n\n`;
  quiz.forEach((q, idx) => {
    md += `#### Question ${idx + 1}: ${q.question}\n\n`;
    (q.options || []).forEach((opt, oIdx) => {
      const letter = String.fromCharCode(65 + oIdx);
      md += `- **[${letter}]** ${opt}\n`;
    });
    md += `\n`;
  });

  md += `---\n\n`;
  md += `## 🔑 Answer Key & Explanations\n\n`;
  quiz.forEach((q, idx) => {
    const correctIdx = q.correctAnswerIndex ?? 0;
    const correctLetter = String.fromCharCode(65 + correctIdx);
    const correctText = (q.options && q.options[correctIdx]) || 'Option ' + correctLetter;
    md += `**Question ${idx + 1}**: Option **[${correctLetter}]** — *${correctText}*\n`;
    md += `> **Explanation**: ${q.explanation || 'Refer to lecture notes.'}\n\n`;
  });

  md += `---\n*Generated by StudyFlow (Client-Side RAG)*\n`;
  return md;
}

export function generatePlainTextContent(studyData) {
  if (!studyData) return '';
  const { filename, notes = [], quiz = [], meta = {} } = studyData;
  let txt = `================================================================================\n`;
  txt += `STUDYFLOW ACADEMIC REVISION SHEET\n`;
  txt += `Document: ${filename || 'Lecture Notes'}\n`;
  txt += `================================================================================\n\n`;

  txt += `PART 1: COMPREHENSIVE NOTES\n`;
  txt += `--------------------------------------------------------------------------------\n\n`;
  notes.forEach((section, idx) => {
    txt += `SECTION ${idx + 1}: ${(section.topic || 'TOPIC').toUpperCase()}\n`;
    (section.points || []).forEach((point) => {
      txt += `  * ${point}\n`;
    });
    txt += `\n`;
  });

  txt += `\nPART 2: PRACTICE QUIZ\n`;
  txt += `--------------------------------------------------------------------------------\n\n`;
  quiz.forEach((q, idx) => {
    txt += `QUESTION ${idx + 1}: ${q.question}\n`;
    (q.options || []).forEach((opt, oIdx) => {
      const letter = String.fromCharCode(65 + oIdx);
      txt += `  [${letter}] ${opt}\n`;
    });
    txt += `\n`;
  });

  txt += `\nPART 3: ANSWER KEY & RATIONALE\n`;
  txt += `--------------------------------------------------------------------------------\n\n`;
  quiz.forEach((q, idx) => {
    const correctIdx = q.correctAnswerIndex ?? 0;
    const correctLetter = String.fromCharCode(65 + correctIdx);
    const correctText = (q.options && q.options[correctIdx]) || 'Option ' + correctLetter;
    txt += `Q${idx + 1} Answer: [${correctLetter}] ${correctText}\n`;
    txt += `   Rationale: ${q.explanation || 'Refer to lecture notes.'}\n\n`;
  });

  return txt;
}
