import React, { useState } from 'react';

function generateMarkdownContent(studyData) {
  const { filename, notes, quiz, meta } = studyData;
  const pers = meta?.personalization;

  let md = `# StudyFlow Revision Guide: ${filename || 'Lecture Material'}\n\n`;

  if (pers?.subject || pers?.academicLevel || pers?.focus) {
    md += `> **Course**: ${pers.subject || 'General'} | **Level**: ${pers.academicLevel || 'Undergraduate'} | **Focus**: ${pers.focus || 'Comprehensive'}\n\n`;
  }

  md += `**Document Metadata**: ${meta?.totalPages || 1} Pages/Slides | ${(meta?.totalWords || 0).toLocaleString()} Words | ${meta?.chunksCount || 0} RAG Chunks | Synthesized with ${meta?.modelUsed || 'Gemini Flash'}\n\n`;
  md += `---\n\n`;

  md += `## 📚 Core Revision Notes\n\n`;
  notes.forEach((section, idx) => {
    md += `### ${idx + 1}. ${section.topic}\n\n`;
    section.points.forEach((point) => {
      md += `- ${point}\n`;
    });
    md += `\n`;
  });

  md += `---\n\n`;
  md += `## 📝 Interactive Multiple-Choice Quiz\n\n`;
  quiz.forEach((q, idx) => {
    md += `#### Question ${idx + 1}: ${q.question}\n\n`;
    q.options.forEach((opt, oIdx) => {
      const letter = String.fromCharCode(65 + oIdx);
      md += `- **[${letter}]** ${opt}\n`;
    });
    md += `\n`;
  });

  md += `---\n\n`;
  md += `## 🔑 Answer Key & Explanations\n\n`;
  quiz.forEach((q, idx) => {
    const correctLetter = String.fromCharCode(65 + q.correctAnswerIndex);
    const correctText = q.options[q.correctAnswerIndex];
    md += `**Question ${idx + 1}**: Option **[${correctLetter}]** — *${correctText}*\n`;
    md += `> **Explanation**: ${q.explanation}\n\n`;
  });

  md += `---\n*Generated by StudyFlow (Client-Side RAG)*\n`;
  return md;
}

function generatePlainTextContent(studyData) {
  const { filename, notes, quiz, meta } = studyData;
  let txt = `================================================================================\n`;
  txt += `STUDYFLOW ACADEMIC REVISION SHEET\n`;
  txt += `Document: ${filename || 'Lecture Notes'}\n`;
  txt += `================================================================================\n\n`;

  txt += `PART 1: COMPREHENSIVE NOTES\n`;
  txt += `--------------------------------------------------------------------------------\n\n`;
  notes.forEach((section, idx) => {
    txt += `SECTION ${idx + 1}: ${section.topic.toUpperCase()}\n`;
    section.points.forEach((point) => {
      txt += `  * ${point}\n`;
    });
    txt += `\n`;
  });

  txt += `\nPART 2: PRACTICE QUIZ\n`;
  txt += `--------------------------------------------------------------------------------\n\n`;
  quiz.forEach((q, idx) => {
    txt += `QUESTION ${idx + 1}: ${q.question}\n`;
    q.options.forEach((opt, oIdx) => {
      const letter = String.fromCharCode(65 + oIdx);
      txt += `  [${letter}] ${opt}\n`;
    });
    txt += `\n`;
  });

  txt += `\nPART 3: ANSWER KEY & RATIONALE\n`;
  txt += `--------------------------------------------------------------------------------\n\n`;
  quiz.forEach((q, idx) => {
    const correctLetter = String.fromCharCode(65 + q.correctAnswerIndex);
    txt += `Q${idx + 1} Answer: [${correctLetter}] ${q.options[q.correctAnswerIndex]}\n`;
    txt += `   Rationale: ${q.explanation}\n\n`;
  });

  return txt;
}

export default function ExportModal({ studyData, onClose }) {
  const [copied, setCopied] = useState(false);

  if (!studyData) return null;

  const baseName = (studyData.filename || 'studyflow_notes').replace(/\.[^/.]+$/, '');

  const triggerDownload = (content, filename, mimeType) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    const md = generateMarkdownContent(studyData);
    triggerDownload(md, `${baseName}_revision_guide.md`, 'text/markdown;charset=utf-8');
  };

  const handleExportText = () => {
    const txt = generatePlainTextContent(studyData);
    triggerDownload(txt, `${baseName}_study_sheet.txt`, 'text/plain;charset=utf-8');
  };

  const handleExportJson = () => {
    const json = JSON.stringify(studyData, null, 2);
    triggerDownload(json, `${baseName}_data.json`, 'application/json;charset=utf-8');
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownContent(studyData);
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="ds-modal-overlay" onClick={onClose}>
      <div className="ds-modal-box export-modal-box" onClick={(e) => e.stopPropagation()}>
        <div className="ds-modal-header">
          <div className="export-modal-title-group">
            <span className="export-modal-kicker">SHARE & EXPORT</span>
            <h3 className="ds-modal-title">Export Study Flow</h3>
          </div>
          <button
            type="button"
            className="ds-modal-close"
            onClick={onClose}
            aria-label="Close"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        <p className="ds-modal-desc">
          Download your detailed revision notes and interactive quiz in shareable academic formats.
        </p>

        <div className="export-options-grid">
          {/* Markdown Option */}
          <div className="export-option-card" onClick={handleExportMarkdown}>
            <div className="export-card-left">
              <span className="export-format-badge">.MD</span>
              <div className="export-info">
                <span className="export-name">Markdown Document</span>
                <span className="export-desc">Full revision guide with notes, quiz questions, and answer key.</span>
              </div>
            </div>
            <button type="button" className="btn-secondary-sm">Download</button>
          </div>

          {/* Plain Text Option */}
          <div className="export-option-card" onClick={handleExportText}>
            <div className="export-card-left">
              <span className="export-format-badge">.TXT</span>
              <div className="export-info">
                <span className="export-name">Plain Study Sheet</span>
                <span className="export-desc">Print-friendly text sheet formatted for offline reading.</span>
              </div>
            </div>
            <button type="button" className="btn-secondary-sm">Download</button>
          </div>

          {/* JSON Option */}
          <div className="export-option-card" onClick={handleExportJson}>
            <div className="export-card-left">
              <span className="export-format-badge">.JSON</span>
              <div className="export-info">
                <span className="export-name">Structured JSON Data</span>
                <span className="export-desc">Raw notes and quiz payload for custom tools or flashcards.</span>
              </div>
            </div>
            <button type="button" className="btn-secondary-sm">Download</button>
          </div>
        </div>

        <div className="export-modal-footer">
          <button
            type="button"
            className="btn-secondary"
            onClick={handleCopyMarkdown}
          >
            {copied ? (
              <>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
                <span>Copied Markdown!</span>
              </>
            ) : (
              <>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
                <span>Copy All to Clipboard</span>
              </>
            )}
          </button>
          <button
            type="button"
            className="btn-primary"
            onClick={onClose}
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
